# GitHub Actions workflow for deploying a static resume to GitHub Pages
name: Deploy Resume to GitHub Pages

on:
  push:
    branches: ["master"]  # Trigger on push to master
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install HTML Validator
        run: npm install -g html-validator-cli

      - name: Run HTML Validation
        run: html-validator --file index.html --verbose

  deploy:
    name: Deploy Resume
    needs: validate  # Ensures validation runs first
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Resume Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Adjust if resume is in a specific folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
